version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin 285951302175.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t economiq-backend .
      - docker tag ecomiq-backend:latest 285951302175.dkr.ecr.us-east-1.amazonaws.com/economiq-backend:latest
  post_build:
    commands:
      - docker push 285951302175.dkr.ecr.us-east-1.amazonaws.com/economiq-backend:latest
      - printf '{"ImageURI":"%s"}' 285951302175.dkr.ecr.us-east-1.amazonaws.com/economiq-backend:latest > imageDetail.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - imageDetail.json
